spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: Mahdi840
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
product:
  list:
    count: 2

wallet:
    balance-url: http://localhost:8081/wallet/balance
    Withdrawal-url: http://localhost:8081/wallet/withdrawal